/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetolojapi;

import Controller.CadastroClienteController;
import DAO.CadastroClienteDAO;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author julio
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    
    private String modoTela;
    public TelaCadastroCliente() {
        initComponents();
        desabilitarFormularioCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoIDCPF = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNumeroResidencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEnderecoRua = new javax.swing.JTextField();
        btnSalvarCadastroCliente = new javax.swing.JButton();
        btnCancelarInclusaoCDcliente = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtEstadoCivil = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtBuscarCliente = new javax.swing.JTextField();
        btnID = new javax.swing.JToggleButton();
        btnCpf = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadastroCliente = new javax.swing.JTable();
        btnNovoCadastroCliente = new javax.swing.JButton();
        btnEditarCadastroCliente = new javax.swing.JButton();
        btnExcluirCadastroCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de clientes");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(11, 33, 47));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("CPF");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Sexo");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Dt. Nasc");

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("E-mail");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Estado Civil");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("CEP");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nº");

        txtNumeroResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroResidenciaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Logradouro");

        btnSalvarCadastroCliente.setForeground(new java.awt.Color(11, 33, 47));
        btnSalvarCadastroCliente.setText("Salvar");
        btnSalvarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroClienteActionPerformed(evt);
            }
        });

        btnCancelarInclusaoCDcliente.setForeground(new java.awt.Color(11, 33, 47));
        btnCancelarInclusaoCDcliente.setText("Cancelar");
        btnCancelarInclusaoCDcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarInclusaoCDclienteActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 204, 204));
        lblNome.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(lblNome)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNome)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnderecoRua))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(btnSalvarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnCancelarInclusaoCDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtNumeroResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtEnderecoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadastroCliente)
                    .addComponent(btnCancelarInclusaoCDcliente))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(19, 54, 77));

        txtBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarClienteActionPerformed(evt);
            }
        });
        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyTyped(evt);
            }
        });

        btnID.setBackground(new java.awt.Color(255, 255, 255));
        GrupoIDCPF.add(btnID);
        btnID.setText("ID");
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });

        btnCpf.setBackground(new java.awt.Color(255, 255, 255));
        GrupoIDCPF.add(btnCpf);
        btnCpf.setText("CPF");
        btnCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnID, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnID)
                    .addComponent(btnCpf))
                .addContainerGap())
        );

        tblCadastroCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID cliente", "Nome", "CPF", "Estado Civil", "Sexo", "Dt. Nasc", "E-mail", "CEP", "Nº", "Logradouro"
            }
        ));
        jScrollPane1.setViewportView(tblCadastroCliente);

        btnNovoCadastroCliente.setBackground(new java.awt.Color(19, 54, 77));
        btnNovoCadastroCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNovoCadastroCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnNovoCadastroCliente.setText("Novo");
        btnNovoCadastroCliente.setBorderPainted(false);
        btnNovoCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCadastroClienteActionPerformed(evt);
            }
        });

        btnEditarCadastroCliente.setBackground(new java.awt.Color(19, 54, 77));
        btnEditarCadastroCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarCadastroCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnEditarCadastroCliente.setText("Editar");
        btnEditarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCadastroClienteActionPerformed(evt);
            }
        });

        btnExcluirCadastroCliente.setBackground(new java.awt.Color(19, 54, 77));
        btnExcluirCadastroCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnExcluirCadastroCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnExcluirCadastroCliente.setText("Excluir");
        btnExcluirCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCadastroClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnNovoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEditarCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(btnExcluirCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtNumeroResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroResidenciaActionPerformed

    private void btnNovoCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCadastroClienteActionPerformed
        // cadastrando o botao "novo" para cadastro do cliente
        
        modoTela = "Inserir";
        habilitarFormularioCliente();
        btnEditarCadastroCliente.setEnabled(false);
        btnExcluirCadastroCliente.setEnabled(false);
        btnCpf.setEnabled(false);
        btnID.setEnabled(false);
        txtBuscarCliente.setEnabled(false);

        //Liberando os campos para o cadastro
        txtCPF.setText("");
        txtSexo.setText("");
        txtDataNascimento.setText("");
        txtEmail.setText("");
        txtEstadoCivil.setText("");
        txtCep.setText("");
        txtNumeroResidencia.setText("");
        txtEnderecoRua.setText("");


    }//GEN-LAST:event_btnNovoCadastroClienteActionPerformed

    public void desabilitarFormularioCliente() {
        btnSalvarCadastroCliente.setEnabled(false);
        txtNome.setEnabled(false);
        txtCPF.setEnabled(false);
        txtSexo.setEnabled(true);
        txtDataNascimento.setEnabled(false);
        txtEmail.setEnabled(false);
        txtEstadoCivil.setEnabled(true);
        txtCep.setEnabled(false);
        txtNumeroResidencia.setEnabled(false);
        txtEnderecoRua.setEnabled(false);
        txtEstadoCivil.setEnabled(false);
        txtSexo.setEnabled(false);

    }

    public void habilitarFormularioCliente() {
        
        btnSalvarCadastroCliente.setEnabled(true);
        txtNome.setEnabled(true);
        txtCPF.setEnabled(true);
        txtSexo.setEnabled(true);
        txtDataNascimento.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEstadoCivil.setEnabled(true);
        txtCep.setEnabled(true);
        txtNumeroResidencia.setEnabled(true);
        txtEstadoCivil.setEnabled(true);
        txtSexo.setEnabled(true);
        txtEnderecoRua.setEnabled(true);

    }

    private void btnSalvarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroClienteActionPerformed
        // Codigo do botao Salvar, cadastro cliente
        if(ValidarFormulario())
        {
            if(modoTela.equals("Inserir"))
            {
                try {
                    //Passo ao controller a entrada do usuário e peço para salvar no banco de dados
                    if(CadastroClienteController.salvar(txtNome.getText(),txtCPF.getText(), txtEstadoCivil.getText(),
                            txtSexo.getText(), txtDataNascimento.getText(), txtEmail.getText(), txtCep.getText(),
                            txtEnderecoRua.getText(), txtNumeroResidencia.getText())){
                        //Recarrego a tabela com os dados resgatados do banco de dados
                        this.CarregarJTable();
                        
                        JOptionPane.showMessageDialog(null,"Cliente cadastrado com sucesso!");
                        LimparFormulario();
                    }else{
                        JOptionPane.showMessageDialog(null,"Falha ao cadastrar cliente!");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                
        
        
        btnEditarCadastroCliente.setEnabled(true);
        btnExcluirCadastroCliente.setEnabled(true);
        txtCPF.setEnabled(false);
        txtNome.setEnabled(false);
        txtSexo.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtEmail.setEnabled(false);
        txtEstadoCivil.setEnabled(false);
        txtCep.setEnabled(false);
        txtNumeroResidencia.setEnabled(false);
        txtEnderecoRua.setEnabled(false);
            }
        }

    }//GEN-LAST:event_btnSalvarCadastroClienteActionPerformed

    public void CarregarJTable(){
        
        //Peço ao controller resgatar os clientes do banco de dados
        ArrayList<String[]> linhasClientes = CadastroClienteController.consultarCliente();
        
        //Opção 1 - Crio manualmente um modelo para a tabela e defino as colunas
        DefaultTableModel tmClientes = new DefaultTableModel();
        //idCliente.setidCliente();
        tmClientes.addColumn("ID");
        tmClientes.addColumn("Nome");
        tmClientes.addColumn("Cpf");
        tmClientes.addColumn("Estado Civil");
        tmClientes.addColumn("Sexo");
        tmClientes.addColumn("Dt.Nasc");
        tmClientes.addColumn("Email");
        tmClientes.addColumn("Cep");
        tmClientes.addColumn("Nº");
        tmClientes.addColumn("Logradouro");
        
        tblCadastroCliente.setModel(tmClientes);
        
        //Removo a coluna da View (JTable) mas mantenho na model para armazenar o ID        
        //Opção 2 - Descomentar linhas abaixo caso queira reutilizar o modelo padrão
        //Resgato o modelo da tabela
        //DefaultTableModel tmClientes = (DefaultTableModel) this.tblClientes.getModel();
        ////Limpo a tabela, excluindo todas as linhas
        //tmClientes.setRowCount(0);
        
        //Para cada cliente resgatado do banco de dados, atualizo a tabela
        for(String[] c:linhasClientes)
        {
            tmClientes.addRow(c);
        }
        
        //Defino o tamanho para cada coluna
        //tblCadastroCliente.getColumnModel().getColumn(0).setPreferredWidth(50); //ID
        tblCadastroCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
    }
    
    private void btnCancelarInclusaoCDclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarInclusaoCDclienteActionPerformed

        desabilitarFormularioCliente();
        btnEditarCadastroCliente.setEnabled(true);
        btnExcluirCadastroCliente.setEnabled(true);
    }//GEN-LAST:event_btnCancelarInclusaoCDclienteActionPerformed

     public void LimparFormulario()
    {
        txtNome.setText("");
        txtCPF.setText("");
        txtCep.setText("");
        txtDataNascimento.setText("");
        txtSexo.setText("");
        txtEstadoCivil.setText("");
        txtEmail.setText("");
        txtNumeroResidencia.setText("");
        txtEnderecoRua.setText("");
        
    }
    
    private void btnEditarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCadastroClienteActionPerformed

        btnEditarCadastroCliente.setEnabled(false);
        btnExcluirCadastroCliente.setEnabled(false);
        habilitarFormularioCliente();
        txtNome.requestFocusInWindow();
    }//GEN-LAST:event_btnEditarCadastroClienteActionPerformed

    private void btnExcluirCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCadastroClienteActionPerformed

    }//GEN-LAST:event_btnExcluirCadastroClienteActionPerformed

    private void txtBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarClienteActionPerformed

    TableRowSorter trs;
    private void txtBuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyTyped

        DefaultTableModel dtm = (DefaultTableModel) (tblCadastroCliente.getModel());
        txtBuscarCliente.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                if (btnID.isSelected()) {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscarCliente.getText() + "(?i)", 0));
                }
                if (btnCpf.isSelected()) {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscarCliente.getText() + "(?i)", 1));
                }
            }
        });

        trs = new TableRowSorter(dtm);
        tblCadastroCliente.setRowSorter(trs);

    }//GEN-LAST:event_txtBuscarClienteKeyTyped

    private void btnCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpfActionPerformed
        txtBuscarCliente.setText("");
    }//GEN-LAST:event_btnCpfActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        txtBuscarCliente.setText("");

    }//GEN-LAST:event_btnIDActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private boolean ValidarFormulario() {
        
        if(this.txtNome.getText().equalsIgnoreCase(""))
        {
            txtNome.setBackground(Color.pink);
            return false;
        }
        
        if(this.txtCPF.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this,"Defina um cpf para cliente!");
            return false;
        }
        if(this.txtCep.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this,"Defina um cep para cliente!");
            return false;
        }
        if(this.txtDataNascimento.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this,"Defina um data de nascimento para cliente!");
            return false;
        }
        if(this.txtEmail.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this,"Defina um e-mail para cliente!");
            return false;
        }
        if(this.txtEnderecoRua.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this,"Defina um endereço para cliente!");
            return false;
        }
        if(this.txtNumeroResidencia.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this,"Defina o número da residência do cliente!");
            return false;
        }
        if(this.txtSexo.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this,"Defina um sexo para cliente!");
            return false;
        }
        if(this.txtEstadoCivil.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(this,"Defina um estado civil para cliente!");
            return false;
        }
        
        /*if(this.txtNome.getText().equalsIgnoreCase("") || this.txtCPF.getText().equalsIgnoreCase("") 
           || this.txtEstadoCivil.getText().equalsIgnoreCase("") || this.txtSexo.getText().equalsIgnoreCase("") 
           || this.txtDataNascimento.getText().equalsIgnoreCase("")  || this.txtEmail.getText().equalsIgnoreCase("") 
           || this.txtEnderecoRua.getText().equalsIgnoreCase("") || this.txtNumeroResidencia.getText().equalsIgnoreCase("")
           ||this.txtCep.getText().equalsIgnoreCase("")){
            
            txtNome.setBackground(Color.pink);
            txtCPF.setBackground(Color.pink);
            txtCep.setBackground(Color.pink);
            txtEmail.setBackground(Color.pink);
            txtNumeroResidencia.setBackground(Color.pink);
            txtSexo.setBackground(Color.pink);
            txtEnderecoRua.setBackground(Color.pink);
            
            JOptionPane.showMessageDialog(this,"Insira os dados nos campos destacados!");
            return false;
    }*/
        
        return true;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoIDCPF;
    private javax.swing.JButton btnCancelarInclusaoCDcliente;
    private javax.swing.JToggleButton btnCpf;
    private javax.swing.JButton btnEditarCadastroCliente;
    private javax.swing.JButton btnExcluirCadastroCliente;
    private javax.swing.JToggleButton btnID;
    private javax.swing.JButton btnNovoCadastroCliente;
    private javax.swing.JButton btnSalvarCadastroCliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblCadastroCliente;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnderecoRua;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumeroResidencia;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
